FROM python:3.11
RUN apt-get update
RUN apt-get install -y python3 python3-pip \
  vim -y

# Defining working Folder.
WORKDIR /app

# Install Application withing Container.
COPY ./src/ /app/

RUN pip install -r requirements.txt

# Adding command to deploy service.
CMD python3 -u train_lstm.py
